
version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./html:/usr/share/nginx/html
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

networks:
  backend:
